import { type NextPage } from "next";
import Head from "next/head";
import Demos from "~/components/Demos";
import Hero from "~/components/hero/Hero";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>E learning</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main>
        <div className="conatiner mx-auto">
          {/* wrapper */}
          <div className="px-4">
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque,
              incidunt enim! Sequi saepe ratione tenetur blanditiis delectus
              eius sint placeat nam recusandae quae dicta, id similique ipsum.
              Consequatur, ipsam impedit?
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
